---
title: "evictions"
author: "Alcides Sorto"
date: "May 11, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown


```{r}
library(sp)
library(rgdal)

source("functions.r")

options(digits=16)

evictions = read.csv("evictions.csv")

polygon.data <- readOGR(dsn=path.expand("sf-tracts"), layer="sf-tracts")



names = polygon.data@data$NAME10

```

## Pull latitude and longitude from evictions file

```{r echo=TRUE}

evict.locations = evictions[,"Client_Location"]


latt <- list()
long <- list()

res = sapply(evict.locations, function(z){
  mach <- gregexpr("-?[[:digit:]]+\\.[[:digit:]]+", z)
  lat = latLong(z,mach,1)
  lng = latLong(z,mach,2)
  return (c(lat,lng))
})

res = t(res)
res = as.data.frame(res)

names(res) <- c("lat", "lng")

```

## Run evictions locations through polygons

```{r}

point.y <- res[,"lng"]
point.x <- res[,"lat"]

points.in <- sapply(polygon.data@polygons, function(poly){
  
  pol.y = poly@Polygons[[1]]@coords[,1]#lon
  pol.x = poly@Polygons[[1]]@coords[,2]#lat
  
  return(point.in.polygon(point.x,point.y,pol.x,pol.y, mode.checked = F))

})



points.in <- as.data.frame(points.in)

names(points.in) <- names

points.in <- t(points.in)
table(points.in)

test <- apply(points.in,1, function(x){sum(x)})


tract.to.evictCount <- data.frame(tract=names,count=test)

write.csv(tract.to.evictCount,"tractToEcivCount.csv", row.names=FALSE)
```

