---
title: "Predicting Crime in San Francisco"
author: "Matt Boensel, Alcides Sorto, Edgar Sandoval"
date: "May 12, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Reading Data
```{r reading in data, message=FALSE, warning=FALSE}
library(sp)
library(rgdal)
library(maps)
library(raster)
library(maptools)
library(ggplot2)
library(ggmap)
library(ROCR)
library(e1071)

source("functions.r")
source("lin-regr-util.R")

crime.data <- read.csv("SFPD_Incidents_-_Previous_Year__2015_.csv")
polygon.data <- readOGR(dsn=path.expand("sf-tracts"), layer="sf-tracts")
weather.data <- read.csv("changed.txt")

options(digits=16)
names = polygon.data@data$NAME10

```

# Preprocessing data
## Enriching with Geospacial Data
```{r preprocessing geospacial data, message=FALSE, warning=FALSE}
#Combining geospacial data
crime.data.locations <- crime.data[,c("Location")]

res = sapply(crime.data.locations, function(z){
  mach <- gregexpr("-?[[:digit:]]+\\.[[:digit:]]+", z)
  lat = latLong(z,mach,1)
  lng = latLong(z,mach,2)
  return (c(lat,lng))
})

res = t(res)
res = as.data.frame(res)
crime.data.locations = data.frame(crime.data.locations, res)
names(crime.data.locations) <- c("Location","lat","lng")

point.y <- crime.data.locations[,"lng"]
point.x <- crime.data.locations[,"lat"]

points.in <- sapply(polygon.data@polygons, function(poly){
  
  pol.y = poly@Polygons[[1]]@coords[,1]#lon
  pol.x = poly@Polygons[[1]]@coords[,2]#lat
  
  return(point.in.polygon(point.x,point.y,pol.x,pol.y, mode.checked = F))

})

points.in <- as.data.frame(points.in)

names(points.in) <- names

crime.point.which <- apply(points.in,1,function(x){ x==1} )

drop <- apply(points.in, 1, function(x){sum(x)==1})

crime.data.locations <- crime.data.locations[drop,]

crime.point.which = t(crime.point.which)

crime.point.which.tract <- (unlist(apply(crime.point.which,1,function(x){ as.character(names[x]) })))

crime.data.locations = data.frame(crime.data.locations,Tract=crime.point.which.tract)

crime.data <- crime.data[drop,]

row.names(crime.data.locations) = NULL
crime.data.locations$Location = NULL

crime.data <- data.frame(crime.data,crime.data.locations)

crime.data$Y = NULL
crime.data$X = NULL
crime.data$Location = NULL

```

## Enriching with weather data
```{r weather data preprocessing, message=FALSE, warning=FALSE}
weather.data <- weather.data[,c("TemperatureF","Conditions","Humidity","Events","date","changedTime")]

weather.data$date <- as.Date(weather.data$date,format="%Y-%m-%d")
weather.data$date <- format(weather.data$date, "%m/%d/%Y")

dates = unlist(lapply(as.character(crime.data$Date), function(x) strsplit(x, "\\s+")[[1]][1]))

crime_dates = as.Date(dates,format = "%m/%d/%Y")
crime.data$Date = format(crime_dates, "%m/%d/%Y")

hours = substr(crime.data$Time, 1,2)
crime.data$Hour = as.numeric(hours)

names(weather.data) = c("TemperatureF", "Conditions" ,  "Humidity"   ,  "Events"   ,    "Date"       ,  "Hour" ) 

test <- merge(crime.data, weather.data, all.x=T)

crime.data = test[!is.na(test$Humidity),]
summary(crime.data)
```

# Data Visualization

```{r data visualization, message=FALSE, warning=FALSE, results="hide"}

polygon.data <- spTransform(polygon.data, CRS("+proj=longlat +datum=WGS84"))
polygon.data <- fortify(polygon.data)
par(mar=c(5,6,3,2))
crime.data$Date = as.Date(crime.data$Date,format = "%m/%d/%Y")

#plots the number of crimes reported per day of the week in jan-dec
months = unique(format(crime.data$Date, "%B"))
par(mar=c(5,6,3,2))
sapply(months, function(m) 
  barplot(table(format(crime.data$Date[format(crime.data$Date, "%B")==m], "%A")),
                                   las=2, horiz = T, main = paste("Crime for", m, "by day of the week"), xlab = "Frequency"))
#default margins
par(mar=c(5.1, 4.1, 4.1, 2.1))

#plots the categories of crimes
par(mar=c(4, 6, 1, 1)+.1)
crime_categories = unique(crime.data$Category)

#plot categories of crimes per month per day of the week
par(cex.axis=1, cex.lab=1, cex.main=1.2, cex.sub=1)
sapply(months, function(m)
  barplot(table(crime.data[format(crime.data$Date, "%B") == m,]$Category), 
          las=2, horiz=T,cex.names=.35, cex.axis = .5, main = paste("Crime Counts for", m), xlab="Frequency"))

hours = substr(crime.data$Time, 1,2)
crime.data$Hour = hours
hours=unique(hours)


#displays the times when crimes occur given their category
par(mar=c(4, 4, 2, 1)+.1)
sapply(crime_categories, function(c)
  barplot(table(crime.data[crime.data$Category == c,]$Hour), main = paste("Times when", c, "has been reported"), xlab = "Hour", ylab="Frequency"))



mean.latitude = mean(crime.data$lat)
mean.longitude = mean(crime.data$lng)

crimes_split = split(as.character(crime_categories),ceiling(seq_along(as.character(crime_categories))/5))

split1 = unlist(crimes_split[1])
split2 = unlist(crimes_split[2])
split3 = unlist(crimes_split[3])
split4 = unlist(crimes_split[4])
split5 = unlist(crimes_split[5])
split6 = unlist(crimes_split[6])
split7 = unlist(crimes_split[7])
split8 = unlist(crimes_split[8])

san_fran = qmap(location=c(mean.longitude, mean.latitude), zoom = 13)
san_fran + stat_density2d(aes(x = lng, y = lat, fill = ..level.., alpha = ..level..), geom ="polygon",data = crime.data[crime.data$Category %in% split1,]) + scale_fill_gradient(low = "yellow", high = "red") + facet_wrap(~ Category) + ggtitle("Locations crimes were reported") + geom_polygon(aes(x=long, y=lat, group=group), fill=NA, size=.2,color='black', data=polygon.data, alpha=.5)

san_fran = qmap(location=c(mean.longitude, mean.latitude), zoom = 13)
san_fran + stat_density2d(aes(x = lng, y = lat, fill = ..level.., alpha = ..level..), geom ="polygon",data = crime.data[crime.data$Category %in% split2,]) + scale_fill_gradient(low = "yellow", high = "red") + facet_wrap(~ Category) + ggtitle("Locations crimes were reported") + geom_polygon(aes(x=long, y=lat, group=group), fill=NA, size=.2,color='black', data=polygon.data, alpha=.5)

san_fran = qmap(location=c(mean.longitude, mean.latitude), zoom = 13)
san_fran + stat_density2d(aes(x = lng, y = lat, fill = ..level.., alpha = ..level..), geom ="polygon",data = crime.data[crime.data$Category %in% split3,]) + scale_fill_gradient(low = "yellow", high = "red") + facet_wrap(~ Category) + ggtitle("Locations crimes were reported") + geom_polygon(aes(x=long, y=lat, group=group), fill=NA, size=.2,color='black', data=polygon.data, alpha=.5)

san_fran = qmap(location=c(mean.longitude, mean.latitude), zoom = 13)
san_fran + stat_density2d(aes(x = lng, y = lat, fill = ..level.., alpha = ..level..), geom ="polygon",data = crime.data[crime.data$Category %in% split4,]) + scale_fill_gradient(low = "yellow", high = "red") + facet_wrap(~ Category) + ggtitle("Locations crimes were reported") + geom_polygon(aes(x=long, y=lat, group=group), fill=NA, size=.2,color='black', data=polygon.data, alpha=.5)

san_fran = qmap(location=c(mean.longitude, mean.latitude), zoom = 13)
san_fran + stat_density2d(aes(x = lng, y = lat, fill = ..level.., alpha = ..level..), geom ="polygon",data = crime.data[crime.data$Category %in% split5,]) + scale_fill_gradient(low = "yellow", high = "red") + facet_wrap(~ Category) + ggtitle("Locations crimes were reported") + geom_polygon(aes(x=long, y=lat, group=group), fill=NA, size=.2,color='black', data=polygon.data, alpha=.5)

san_fran = qmap(location=c(mean.longitude, mean.latitude), zoom = 13)
san_fran + stat_density2d(aes(x = lng, y = lat, fill = ..level.., alpha = ..level..), geom ="polygon",data = crime.data[crime.data$Category %in% split6,]) + scale_fill_gradient(low = "yellow", high = "red") + facet_wrap(~ Category) + ggtitle("Locations crimes were reported") + geom_polygon(aes(x=long, y=lat, group=group), fill=NA, size=.2,color='black', data=polygon.data, alpha=.5)

san_fran = qmap(location=c(mean.longitude, mean.latitude), zoom = 13)
san_fran + stat_density2d(aes(x = lng, y = lat, fill = ..level.., alpha = ..level..), geom ="polygon",data = crime.data[crime.data$Category %in% split7,]) + scale_fill_gradient(low = "yellow", high = "red") + facet_wrap(~ Category) + ggtitle("Locations crimes were reported") + geom_polygon(aes(x=long, y=lat, group=group), fill=NA, size=.2,color='black', data=polygon.data, alpha=.5)

san_fran = qmap(location=c(mean.longitude, mean.latitude), zoom = 13)
san_fran + stat_density2d(aes(x = lng, y = lat, fill = ..level.., alpha = ..level..), geom ="polygon",data = crime.data[crime.data$Category %in% split8,]) + scale_fill_gradient(low = "yellow", high = "red") + facet_wrap(~ Category) + ggtitle("Locations crimes were reported") + geom_polygon(aes(x=long, y=lat, group=group), fill=NA, size=.2,color='black', data=polygon.data, alpha=.5)
```

# Building Model

```{r}
#split data confusion matrix, double density plot, when predit name varivles predicted

tract = unique(crime.data$Tract)
single_tract = crime.data[crime.data$Tract == "117",]
single_tract$output = as.numeric(single_tract$Category == "ROBBERY")

set.seed(123)

data.split = split_data(single_tract)


tr_data = data.split[[1]]
te_dat = data.split[[2]]

fit = glm(output ~ Events + Humidity + Conditions + TemperatureF + DayOfWeek + Hour, data = tr_data, family = binomial)



summary(fit)

predicted = predict(fit, newdata=te_dat , type = "response")

plot(density(predicted[te_dat$output == 0]), col="green", main="Double Density Plot")
lines(density(predicted[te_dat$output == 1]), col="red")
thresh = .05
abline(v=thresh, lty=2, col="blue")


predicted_vals = as.numeric(predicted < thresh)
actuals = te_dat$output
conf_matrix = table(actuals, predicted_vals)
conf_matrix
```

```{r analysis of the model}
crime_predictions = prediction(predicted, te_dat$output)
roc = performance(crime_predictions, measure = "tpr", x.measure = "fpr")
prec_recall = performance(crime_predictions, measure="prec", x.measure="rec")
acc_curve = performance(crime_predictions, measure = "acc", x.measure = "cutoff")


plot(acc_curve, main="Accuracy Threshold Curve")
plot(prec_recall, main = "Precision Recall Curve")
plot(roc, main="Receiver Operating Characteristic",col="blue")
```


```{r}
crime.data$output = NULL
splits3 = split_data(crime.data)
tr_dat = splits3[[1]]
te_dat = splits3[[2]]

fit3 = rpart(Category ~ Events + Humidity + Conditions + TemperatureF + DayOfWeek + Hour + Tract, data = tr_dat, method="class")
summary(fit3)
prp(fit3, extra = 106, varlen = -10, main="Classification tree for crime fit3", box.col = c("palegreen", "pink")[fit$frame$yval])

```

